### ISSUE TITLE
Invalid latitude Error for some IO collections when using `stackstac`

### ISSUE THREAD

**Issue by vcameron1** [ReseauBiodiversiteQuebec/stac-catalogue#6]
When using the stac-catalogue with python, the equivalent to `gdalcubes` is the `stackstac` library. The library works fine with the catalogue "IO", except for some collections, namely `pither_functional_connectivity`, `aafc_land_use`, and `canadian_human_footprint`.

Here is an example with the `pither_functional_connectivity` collection when querying for items that overlap with a given polygon. The polygon's geoJSON is provided in "EPSG:3347" projection.

```python
#==============================================================================
# Try the data cube approach
#
# Required variables:
#
# collection = "pither_functional_connectivity"
# catalog_url = "http://coleo-api.vhost33:8082/"
## Polygon in 3347
# polygon = {"coordinates": [[[7754757.019763, 1271146.883591], [7754943.195872, 1271083.567652], [7755012.741353, 1271289.428728], [7754861.494634, 1271338.924423], [7754852.088722, 1271339.123262], [7754844.377813, 1271337.846169], [7754838.493815, 1271335.944864], [7754831.991932, 1271333.439812], [7754826.700741, 1271329.705254], [7754822.866762, 1271325.228681], [7754817.693157, 1271321.127758], [7754815.319004, 1271315.907982], [7754757.019763, 1271146.883591]]], "type": "Polygon"}
#==============================================================================
import pystac_client
import stackstac

catalog = pystac_client.Client.open(catalog_url)

# Create the datacube
## NOTE: the polygon must match the items' projection
items = catalog.search(
    intersects=polygon,
    collections=[collection]
).item_collection()
len(items)

stack = stackstac.stack(items)
```

Result:
```
>>> stack = stackstac.stack(items)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/camv2202/bq_impact_indicators/.venv/lib/python3.10/site-packages/stackstac/stack.py", line 290, in stack
    asset_table, spec, asset_ids, plain_items = prepare_items(
  File "/home/camv2202/bq_impact_indicators/.venv/lib/python3.10/site-packages/stackstac/prepare.py", line 260, in prepare_items
    asset_bbox_proj = geom_utils.reproject_bounds(
  File "/home/camv2202/bq_impact_indicators/.venv/lib/python3.10/site-packages/stackstac/geom_utils.py", line 52, in reproject_bounds
    xs_proj, ys_proj = transformer.transform(xs, ys, errcheck=True)  # TODO handle error
  File "/home/camv2202/bq_impact_indicators/.venv/lib/python3.10/site-packages/pyproj/transformer.py", line 840, in transform
    self._transformer._transform(
  File "pyproj/_transformer.pyx", line 707, in pyproj._transformer._Transformer._transform
pyproj.exceptions.ProjError: transform error: Invalid coordinate: (Internal Proj Error: lcc: Invalid latitude)
```

Food for thoughts
- `aafc_land_use` collection may fail because each item has a different projection ?
- No clue why `canadian_human_footprint` or `pither_functional_connectivity` fails
- 

### Working example:

Another collection (that works !):
```python
collection = "gbif_heatmaps"
## Polygon in 4326
polygon = { "type": "Polygon", "coordinates": [ [ [ -71.989021573308534, 45.404000415469056 ], [ -71.987038174572334, 45.402959401362089 ], [ -71.98540963380141, 45.404505556821491 ], [ -71.987028443356962, 45.40533493226846 ], [ -71.987140253500854, 45.405362234064313 ], [ -71.987237484510757, 45.405372474057657 ], [ -71.987315263440109, 45.405372473936815 ], [ -71.987402772819166, 45.405369066780658 ], [ -71.987480546508735, 45.405351995013334 ], [ -71.987543748498041, 45.405324697182159 ], [ -71.987621531580913, 45.405304216052308 ], [ -71.987670135059872, 45.405266675018261 ], [ -71.989021573308534, 45.404000415469056 ] ] ] }
```

**Comment by glaroc** [comment]
The bounding boxes and geometries of the items had to be in wgs84. I changed all the items on io and acer that were not in wgs84. All should be good now.

**Comment by glaroc** [comment]
Note that this repo will be closed eventually. Please use bq-stac instead.
